---
- name: Clone a virtual machine from template.
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vm_datastore }}"
    resource_pool: "{{ customer | lower }}-{{ environments | lower }}-{{ group_names[-1] | lower }}-{{ group_names[0] | lower }}"
    folder: "{{ customer | lower }}/{{ environments | lower }}/{{ group_names[-1] | lower }}/{{ group_names[0] | lower }}"
    name: "{{ inventory_hostname | lower }}"
    template: "{{ vm_template }}"
    state: "poweredoff"
    hardware:
      memory_mb: "{{ vm_memory | int * 1024 }}"
      num_cpus: "{{ vm_cpucount | int }}"
    networks:
      - name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ item.gateway }}"
        type: "{{ item.type }}"
    customization:
      hostname: "{{ inventory_hostname | lower }}"
      domain: "node.{{ datacenter }}.{{ domain }}"
      dns_suffix: "{{ datacenter }}.{{ domain }}"
      dns_servers: "{{ vm_dns_server }}"
      password: "{{ vm_password | default(null) }}"
    wait_for_ip_address: "yes"
    validate_certs: false
  loop: "{{ vm_networks | default([{'name':vm_network,'ip':ansible_host,'netmask':vm_netmask,'gateway':vm_gateway,'type':'static'}]) }}"
  delegate_to: localhost

- name: Add tags to a virtual machine.
  community.vmware.vmware_tag_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    tag_names: "{{ vm_tags }}"
    object_name: "{{ inventory_hostname | lower }}"
    object_type: VirtualMachine
    state: add
    validate_certs: false
  delegate_to: localhost
  when: vm_tags is defined

- name: Manage disks related to virtual machine.
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ vcenter_datacenter }}/vm/{{ customer | lower }}/{{ environments | lower }}/{{ group_names[-1] | lower }}/{{ group_names[0] | lower }}"
    name: "{{ inventory_hostname | lower }}"
    disk:
      - size_gb: "{{ item.size_gb }}"
        type: "{{ item.type | default('thin') }}"
        datastore: "{{ vm_datastore }}"
        controller_number: "{{ item.controller_number | default(0) }}"
        controller_type: "{{ item.controller_type | default('paravirtual') }}"
        state: present
        unit_number: "{{ item.unit_number }}"
    validate_certs: false
  loop: "{{ vm_disks }}"
  delegate_to: localhost
