---
- name: Clone a virtual machine from template.
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vm_datastore }}"
    resource_pool: "{% if vm_rp_info | json_query('*.name') | length > 0 %}rg-{{ customer | lower }}-{{ environments | lower }}-{{ group_names[-1] | lower }}-{{ group_names[0] | lower }}{% endif %}"
    folder: "{{ customer | lower }}/{{ environments | lower }}/{{ group_names[-1] | lower }}/{{ group_names[0] | lower }}"
    name: "{{ inventory_hostname | lower }}"
    template: "{{ vm_template }}"
    state: "poweredon"
    hardware:
      memory_mb: "{{ vm_memory | int * 1024 }}"
      num_cpus: "{{ vm_cpucount | int }}"
    networks:
      - name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ item.gateway }}"
        type: "{{ item.type }}"
    customization:
      hostname: "{{ inventory_hostname | lower }}"
      domain: "node.{{ datacenter }}.{{ domain }}"
      dns_suffix: "{{ datacenter }}.{{ domain }}"
      dns_servers: "{{ vm_dns_server }}"
      password: "{{ vm_password | default(null) }}"
    wait_for_ip_address: "yes"
    validate_certs: false
  loop: "{{ vm_networks | default([{'name':vm_network,'ip':ansible_host,'netmask':vm_netmask,'gateway':vm_gateway,'type':'static'}]) }}"
  delegate_to: localhost
